apiVersion: v1
data:
  ASYNCTIMEOUT: "600"
  BATCHTHREADS: "3"
  BROKER_HOSTPORT_FROM: ""
  BROKER_HOSTPORT_TO: ""
  BROKER_USERNAME_PASS_FROM: ""
  BROKER_USERNAME_PASS_TO: ""
  CLOUD_PASSWORD: Zo0a+IDBkHlg47JbO9OEWV9/wJgL8mA6n1ZA9DJ6JqQmUkVJ11ihVhdR7rg9afQr
  CLOUD_USERNAME: PH4QHCVPVWB7UOLB
  COMPANYNAME: ""
  COMPRESSION_FROM: ""
  COMPRESSION_TO: ""
  COMPRESSIONTYPE: SNAPPY
  ENABLETLS_FROM: ""
  ENABLETLS_TO: ""
  FILEAGEMAX: "5"
  KAFKA_ADVERTISED_HOST_NAME: kafka
  KAFKA_CONNECT_BOOTSTRAP_SERVERS: pkc-6ojv2.us-west4.gcp.confluent.cloud:9092
  KAFKA_ZOOKEEPER_CONNECT: ""
  KUBERNETES: "0"
  LOGSTREAMTOPIC: ""
  LOGSTREAMTOPICPARTITIONS: ""
  LOGSTREAMTOPICREPLICATIONFACTOR: ""
  MAXBROKERSPERCONTAINER: "1"
  MAXCONSUMEMESSAGES: "3000"
  MAXOPENREQUESTS: "10"
  MAXPERCMESSAGES: "3000"
  MAXPREDICTIONROWS: "500"
  MAXPREPROCESSMESSAGES: "3000"
  MAXTRAININGROWS: "500"
  MAXVIPERVIZCONNECTIONS: "5"
  MAXVIPERVIZROLLBACKOFFSET: "300"
  MICROSERVICEID: ""
  NAME: OTICS
  ONPREM: "0"
  PARTITION_CHANGE_PERC: "0"
  PARTITIONS: ""
  POLLING_ALERTS: "120"
  REPLICATIONFACTOR_FROM: ""
  REPLICATIONFACTOR_TO: ""
  SASL_FROM: ""
  SASL_TO: ""
  SASLMECHANISM: PLAIN
  SERVICENAME_FROM: KAFKA Migration to Redpanda
  SERVICENAME_TO: KAFKA Migration to Redpanda
  SSL_CLIENT_CERT_FILE: client.cer.pem
  SSL_CLIENT_KEY_FILE: client.key.pem
  SSL_SERVER_CERT_FILE: server.cer.pem
  SYNC_INTERVAL: "10"
  TOPIC_FILTER: ""
  TOPICS_LIST_FROM: ""
  USEHTTP: "0"
  VIPERDEBUG: "2"
  WRITETOVIPERDB: "0"
  replicationchange: "0"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: otics-mirrorbrokers-viper-generic-env
  name: viper-generic-env
